# Generated by Django 5.2.8 on 2025-12-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التنبيه')),
                ('message', models.TextField(verbose_name='رسالة التنبيه')),
                ('level', models.CharField(choices=[('WARNING', 'تحذير'), ('CRITICAL', 'خطر')], default='WARNING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الحل')),
                ('content', models.TextField(verbose_name='نص الحل المقترح')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ABSHER', 'بوابة أبشر'), ('TWITTER', 'منصة X (تويتر)'), ('EMAIL', 'البريد الإلكتروني')], default='ABSHER', max_length=20, verbose_name='المصدر')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع الخارجي')),
                ('user_name', models.CharField(default='مجهول', max_length=100, verbose_name='اسم المستفيد')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='تحليل الذكاء الاصطناعي')),
                ('suggested_solution', models.TextField(blank=True, null=True, verbose_name='الحل المقترح')),
                ('status', models.CharField(choices=[('NEW', 'جديد'), ('AI_PROCESSED', 'تم تحليله ذكياً'), ('USER_ACTION_REQUIRED', 'بانتظار رد المستفيد'), ('ESCALATED', 'مرفوع للموظف'), ('RESOLVED', 'تم الحل')], default='NEW', max_length=30, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='التصنيف المتوقع')),
            ],
            options={
                'verbose_name': 'تذكرة',
                'verbose_name_plural': 'التذاكر',
                'ordering': ['-created_at'],
            },
        ),
    ]
