# Generated by Django 5.2.8 on 2025-12-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التنبيه')),
                ('message', models.TextField(verbose_name='رسالة التنبيه')),
                ('level', models.CharField(choices=[('WARNING', 'تحذير'), ('CRITICAL', 'خطر')], default='WARNING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة المجمعة')),
                ('category', models.CharField(default='عام', max_length=100, verbose_name='التصنيف الرئيسي')),
                ('ai_summary', models.TextField(blank=True, verbose_name='ملخص الذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الحل')),
                ('content', models.TextField(verbose_name='نص الحل المقترح')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='main.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TWITTER', 'Twitter'), ('CHATBOT', 'Chatbot'), ('CALL_CENTER', 'Call Center'), ('EMAIL', 'Email'), ('ABSHER', 'Absher Portal')], default='ABSHER', max_length=20, verbose_name='المصدر')),
                ('user_name', models.CharField(default='مجهول', max_length=100, verbose_name='اسم المستفيد')),
                ('description', models.TextField(verbose_name='نص الشكوى')),
                ('confidence_score', models.IntegerField(default=0, verbose_name='نسبة الثقة')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='تحليل AI')),
                ('suggested_solution', models.TextField(blank=True, null=True, verbose_name='الحل المقترح')),
                ('retry_count', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('status', models.CharField(choices=[('NEW', 'جديد'), ('AI_PROCESSED', 'تم تحليله ذكياً'), ('SOLVED', 'تم الحل'), ('ESCALATED', 'مرفوع للموظف')], default='NEW', max_length=30, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.cluster')),
            ],
        ),
    ]
