# Generated by Django 5.2.8 on 2025-12-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة المجمعة')),
                ('category', models.CharField(default='عام', max_length=100, verbose_name='التصنيف الرئيسي')),
                ('ai_summary', models.TextField(blank=True, verbose_name='ملخص الذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solution',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='suggested_solution',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='confidence_score',
            field=models.IntegerField(default=0, verbose_name='نسبة الثقة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='تحليل AI'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='نص الشكوى'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('TWITTER', 'منصة X (تويتر)'), ('CHATBOT', 'شات بوت'), ('CALL_CENTER', 'مركز الاتصال'), ('EMAIL', 'البريد الإلكتروني'), ('ABSHER', 'بوابة أبشر')], default='ABSHER', max_length=20, verbose_name='المصدر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديد'), ('AI_PROCESSED', 'تم تحليله ذكياً'), ('SOLVED', 'تم الحل'), ('ESCALATED', 'مرفوع للموظف')], default='NEW', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='solution',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='main.cluster'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.cluster', verbose_name='المشكلة المرتبطة'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
