# Generated by Django 5.2.8 on 2025-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cluster_remove_solution_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='ticket',
            name='suggested_solution',
            field=models.TextField(blank=True, null=True, verbose_name='الحل المقترح'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(default='مجهول', max_length=100, verbose_name='اسم المستفيد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='تحليل الذكاء الاصطناعي'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='وصف المشكلة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('ABSHER', 'بوابة أبشر'), ('TWITTER', 'منصة X (تويتر)'), ('EMAIL', 'البريد الإلكتروني')], default='ABSHER', max_length=20, verbose_name='المصدر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديد'), ('AI_PROCESSED', 'تم تحليله ذكياً'), ('USER_ACTION_REQUIRED', 'بانتظار رد المستفيد'), ('ESCALATED', 'مرفوع للموظف'), ('RESOLVED', 'تم الحل')], default='NEW', max_length=30, verbose_name='الحالة'),
        ),
    ]
