# Generated by Django 5.2.8 on 2025-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة')),
                ('count', models.IntegerField(default=1, verbose_name='عدد التكرار')),
                ('confidence', models.IntegerField(default=80, verbose_name='ثقة AI')),
                ('source', models.CharField(default='تويتر', max_length=100, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
