# Generated by Django 5.2.8 on 2025-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='source',
        ),
        migrations.AddField(
            model_name='cluster',
            name='ai_summary',
            field=models.TextField(blank=True, verbose_name='ملخص الذكاء الاصطناعي (السؤال العام)'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='category',
            field=models.CharField(default='عام', max_length=100, verbose_name='التصنيف الرئيسي'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تم الاعتماد'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المشكلة المجمعة'),
        ),
    ]
